apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "springboot-chart.fullname" . }}
  labels:
    {{- include "springboot-chart.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
    # Enable IP tracking in metrics
    rollout.argoproj.io/metrics: |
      - name: request-source-ips
        interval: 30s
        provider:
          prometheus:
            address: http://prometheus-service:9090
            query: |
              count by (source_ip) (
                http_requests_total{
                  namespace="{{ .Release.Namespace }}",
                  service="{{ include "springboot-chart.fullname" . }}",
                  version="canary"
                }
              )

spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "springboot-chart.selectorLabels" . | nindent 6 }}
  strategy:
    canary:
      # Service reference for traffic splitting
      canaryService: "springboot-demo-canary"
      stableService: "springboot-demo-stable"
      trafficRouting:
      istio:
        virtualService:
          name: samplecharts-dev-springboot-chart-virtualservice
          routes:
            - http
      steps:
        - setWeight: 25
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 100
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "springboot-chart.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        # Add version label for tracking
        version: "{{ .Values.image.tag | default .Chart.AppVersion }}"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "springboot-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- if .Values.healthCheck.enabled }}
          readinessProbe:
            {{- toYaml .Values.healthCheck.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.healthCheck.livenessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          # Add IP tracking environment variable
          env:
            - name: TRACK_SOURCE_IPS
              value: "true"
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
