apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceNames.stable | default "springboot-stable" }}
  labels:
    {{- include "springboot-chart.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.containerPort }}
  selector:
    {{- include "springboot-chart.selectorLabels" . | nindent 4 }}


