apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: samplecharts-dev-springboot-chart-virtualservice
  namespace: dev
spec:
  hosts:
    - 'samplecharts-dev-springboot-chart.dev.svc.cluster.local'
  http:
    - route:
        - destination:
            host: samplecharts-dev-springboot-chart-stable
          weight: 100
        - destination:
            host: samplecharts-dev-springboot-chart-canary
          weight: 0
