{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.istio.virtualService.name }}
spec:
  hosts:
    - "{{ .Values.istio.host }}"
  gateways:
    - "{{ .Values.istio.gateway }}"
  http:
    {{- toYaml .Values.istio.virtualService.http | nindent 4 }}
{{- end }}
