<<<<<<< HEAD
{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.istio.virtualService.name }}
spec:
  hosts:
    - "{{ .Values.istio.host }}"
  gateways:
    - "{{ .Values.istio.gateway }}"
  http:
    - name: primary
      route:
        - destination:
            host: {{ include "springboot-chart.fullname" . }}-stable.{{ .Release.Namespace }}.svc.cluster.local
          weight: 100
        - destination:
            host: {{ include "springboot-chart.fullname" . }}-canary.{{ .Release.Namespace }}.svc.cluster.local
          weight: 0
{{- end }}
=======
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: samplecharts-dev-springboot-chart-virtualservice
  namespace: dev
spec:
  hosts:
    - 'samplecharts-dev-springboot-chart.dev.svc.cluster.local'
  http:
    - name: primary  # Add this name field
      route:
        - destination:
            host: springboot-demo-stable  # Changed to match your actual service
          weight: 100
        - destination:
            host: springboot-demo-canary  # Changed to match your actual service
          weight: 0
>>>>>>> 21ddd0b1868fa543f04896b22eaabc73a06e99b5
