apiVersion: apps/v1
kind: Deployment
metadata:
  name: cherry-backend
spec:
  selector:
    matchLabels:
      app: cherry-backend
  template:
    metadata:
      labels:
        app: cherry-backend
    spec:
      containers:
        - name: cherry-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: DATABASE_URL
              value: "mysql://$(DB_USER):$(DB_PASSWORD)@mysql:$(DB_PORT)/$(DB_NAME)"
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "{{ .Values.mysql.port }}"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret-{{ .Release.Namespace }}  # Namespace-specific
                  key: mysql-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret-{{ .Release.Namespace }}
                  key: mysql-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret-{{ .Release.Namespace }}
                  key: mysql-database
