apiVersion: v1
kind: Service
metadata:
  name: cherry-backend
spec:
  type: {{ .Values.service.backendType }}
  selector:
    app: cherry-backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
