apiVersion: v1
kind: Service
metadata:
  name: cherry-frontend
spec:
  type: {{ .Values.service.frontendType }}
  selector:
    app: cherry-frontend
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.port }}
