apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  mysql-root-password: {{ .Values.mysql.rootPassword | quote }}
  mysql-user: {{ .Values.mysql.user | quote }}
  mysql-password: {{ .Values.mysql.password | quote }}
  mysql-database: {{ .Values.mysql.database | quote }}

