backend:
  image:
    repository: iyuyisenga/cherry-app-backend-test
    tag: v1.1.8
  port: 3000

frontend:
  image:
    repository: iyuyisenga/cherry-app-frontend-test
    tag: main
    pullPolicy: IfNotPresent
  port: 5173

mysql:
  image: mysql:8
  rootPassword: "rootpassword"  # Ensure quoted strings
  database: "cherrydb"
  user: "cherryuser"
  password: "cherrypassword"
  port: 3306
  storage: 5Gi

service:
  backendType: ClusterIP
  frontendType: ClusterIP

